/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109989-g7a8560cb22-20230310"
#endif /* AVUTIL_FFVERSION_H */
